# Generated by Django 5.2.4 on 2025-07-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_purchase_purchase_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
