# Generated by Django 5.2.4 on 2025-07-28 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_current_stock_alter_product_image_url'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(default='90caf1ce-8876-417a-8bd0-1bf236df9858', on_delete=django.db.models.deletion.PROTECT, to='products.product'),
            preserve_default=False,
        ),
    ]
