# Generated by Django 5.2.4 on 2025-07-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saledetail_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='sale_state',
        ),
        migrations.AddField(
            model_name='salebill',
            name='bill_state',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_state',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale_state',
            field=models.SmallIntegerField(default=1),
        ),
    ]
