# Generated by Django 5.2.4 on 2025-07-28 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_salebill_bill_state_alter_salebill_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='sales.sale'),
        ),
    ]
