# Generated by Django 5.2.4 on 2025-07-31 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_salebill_sale'),
        ('usuarios', '0002_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1900-03-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salebill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='client',
            field=models.ForeignKey(blank=True, default='CF', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.client'),
        ),
    ]
