# Generated by Django 5.2.4 on 2025-07-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salebill_created_at_salebill_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
